# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-11-09 04:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ctime', models.DateTimeField(auto_now=True)),
                ('utime', models.DateTimeField(auto_now_add=True)),
                ('mon_title', models.CharField(max_length=100, unique=True)),
                ('mon_type', models.PositiveSmallIntegerField(choices=[(1, '\u57fa\u7840'), (2, '\u8d26\u52a1\u7cfb\u7edf'), (3, '\u98ce\u63a7\u7cfb\u7edf'), (4, '\u4e09\u65b9\u63a5\u53e3')])),
                ('mon_trigger', models.PositiveSmallIntegerField()),
                ('mon_desc', models.CharField(blank=True, default='', max_length=1024)),
                ('mon_status', models.PositiveSmallIntegerField(default=1)),
            ],
            options={
                'ordering': ('mon_type',),
            },
        ),
    ]
