# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-11-12 05:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ctime', models.DateTimeField(auto_now_add=True)),
                ('utime', models.DateTimeField(auto_now=True)),
                ('gro_name', models.CharField(max_length=100, unique=True)),
                ('notify_phone_no', models.CharField(default='', max_length=1024)),
                ('notify_email', models.CharField(default='', max_length=1024)),
                ('notify_wechat', models.CharField(default='', max_length=1024)),
                ('gro_desc', models.CharField(blank=True, default='', max_length=1024)),
                ('gro_status', models.PositiveSmallIntegerField(default=1)),
            ],
            options={
                'ordering': ('ctime',),
            },
        ),
        migrations.CreateModel(
            name='GroupItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ctime', models.DateTimeField(auto_now_add=True)),
                ('utime', models.DateTimeField(auto_now=True)),
                ('gro_id', models.PositiveIntegerField()),
                ('mon_id', models.PositiveIntegerField()),
            ],
            options={
                'ordering': ('ctime',),
                'db_table': 'monitor_group_item',
            },
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ctime', models.DateTimeField(auto_now_add=True)),
                ('utime', models.DateTimeField(auto_now=True)),
                ('mon_title', models.CharField(max_length=100, unique=True)),
                ('mon_type', models.PositiveSmallIntegerField(choices=[(3, '\u98ce\u63a7\u7cfb\u7edf'), (4, '\u4e09\u65b9\u63a5\u53e3'), (2, '\u8d26\u52a1\u7cfb\u7edf'), (1, '\u57fa\u7840')])),
                ('mon_trigger', models.CharField(max_length=100)),
                ('mon_trigger_desc', models.CharField(default='', max_length=255)),
                ('mon_desc', models.CharField(blank=True, default='', max_length=1024)),
                ('mon_status', models.PositiveSmallIntegerField(default=1)),
            ],
            options={
                'ordering': ('mon_type',),
            },
        ),
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ctime', models.DateTimeField(auto_now_add=True)),
                ('utime', models.DateTimeField(auto_now=True)),
                ('mon_id', models.PositiveIntegerField()),
                ('mon_type', models.PositiveIntegerField(default=0)),
                ('mon_title', models.CharField(max_length=100)),
                ('mon_status', models.PositiveSmallIntegerField(choices=[(3, '\u6062\u590d'), (2, '\u544a\u8b66\u4e2d'), (1, '\u6b63\u5e38')], default=1)),
                ('mon_level', models.PositiveSmallIntegerField(default=0)),
                ('err_info', models.CharField(blank=True, default='', max_length=1024)),
                ('remark', models.CharField(blank=True, default='', max_length=1024)),
                ('operator', models.CharField(blank=True, default='', max_length=256)),
            ],
            options={
                'ordering': ('-utime',),
            },
        ),
        migrations.CreateModel(
            name='ItemVo',
            fields=[
                ('item_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='monitor.Item')),
            ],
            bases=('monitor.item',),
        ),
    ]
