# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-11-12 06:02
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='record',
            options={'get_latest_by': 'utime', 'ordering': ('-utime',)},
        ),
    ]
