# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-11-09 06:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0002_auto_20181109_1242'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='mon_trigger_desc',
            field=models.CharField(default='', max_length=255),
        ),
    ]
