# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-11-13 03:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0002_auto_20181112_1402'),
    ]

    operations = [
        migrations.RenameField(
            model_name='group',
            old_name='notify_email',
            new_name='notify_wx_tags',
        ),
        migrations.RemoveField(
            model_name='group',
            name='notify_phone_no',
        ),
        migrations.RemoveField(
            model_name='group',
            name='notify_wechat',
        ),
    ]
