# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-11-13 03:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0003_auto_20181113_1141'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='notify_wx_tags_id',
            field=models.CharField(default='', max_length=1024),
        ),
    ]
