# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-11-09 11:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0003_item_mon_trigger_desc'),
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ctime', models.DateTimeField(auto_now=True)),
                ('utime', models.DateTimeField(auto_now_add=True)),
                ('gro_name', models.CharField(max_length=100, unique=True)),
                ('notify_phone_no', models.CharField(default='', max_length=1024)),
                ('notify_email', models.CharField(default='', max_length=1024)),
                ('gro_desc', models.CharField(blank=True, default='', max_length=1024)),
                ('gro_status', models.PositiveSmallIntegerField(default=1)),
            ],
            options={
                'ordering': ('ctime',),
            },
        ),
        migrations.CreateModel(
            name='GroupItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ctime', models.DateTimeField(auto_now=True)),
                ('utime', models.DateTimeField(auto_now_add=True)),
                ('gro_id', models.PositiveIntegerField()),
                ('item_id', models.PositiveIntegerField()),
            ],
            options={
                'ordering': ('ctime',),
            },
        ),
    ]
