# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-11-09 11:01
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0004_group_groupitem'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='GroupItem',
            new_name='Group_item',
        ),
    ]
