# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-11-21 03:23
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0004_group_notify_wx_tags_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='free_date',
            field=models.DateField(default=datetime.date(2018, 11, 20)),
        ),
        migrations.AlterField(
            model_name='item',
            name='mon_type',
            field=models.PositiveSmallIntegerField(choices=[(1, '\u57fa\u7840'), (2, '\u8d26\u52a1\u7cfb\u7edf'), (4, '\u4e09\u65b9\u63a5\u53e3'), (3, '\u98ce\u63a7\u7cfb\u7edf')]),
        ),
    ]
