# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-11-22 12:01
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0005_auto_20181121_1123'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='free_data',
            field=models.CharField(default='', max_length=1000),
        ),
        migrations.AlterField(
            model_name='item',
            name='free_date',
            field=models.DateField(default=datetime.date(2018, 11, 21)),
        ),
    ]
