# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-11-09 11:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0005_auto_20181109_1901'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemVo',
            fields=[
                ('item_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='monitor.Item')),
            ],
            bases=('monitor.item',),
        ),
        migrations.RenameModel(
            old_name='Group_item',
            new_name='GroupItem',
        ),
        migrations.AlterModelTable(
            name='groupitem',
            table='monitor_group_item',
        ),
    ]
