# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-11-10 11:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0006_auto_20181109_1941'),
    ]

    operations = [
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ctime', models.DateTimeField(auto_now=True)),
                ('utime', models.DateTimeField(auto_now_add=True)),
                ('item_id', models.PositiveIntegerField()),
                ('mon_title', models.CharField(max_length=100, unique=True)),
                ('mon_status', models.PositiveSmallIntegerField(choices=[(1, '\u6b63\u5e38'), (2, '\u544a\u8b66\u4e2d'), (3, '\u6062\u590d')], default=1)),
                ('mon_level', models.PositiveSmallIntegerField(default=0)),
                ('remark', models.CharField(blank=True, default='', max_length=1024)),
            ],
            options={
                'ordering': ('-utime',),
            },
        ),
    ]
