# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-11-10 12:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0008_auto_20181110_2016'),
    ]

    operations = [
        migrations.RenameField(
            model_name='record',
            old_name='item_id',
            new_name='mon_id',
        ),
        migrations.AlterField(
            model_name='item',
            name='mon_type',
            field=models.PositiveSmallIntegerField(choices=[(3, '\u98ce\u63a7\u7cfb\u7edf'), (4, '\u4e09\u65b9\u63a5\u53e3'), (2, '\u8d26\u52a1\u7cfb\u7edf'), (1, '\u57fa\u7840')]),
        ),
        migrations.AlterField(
            model_name='record',
            name='mon_status',
            field=models.PositiveSmallIntegerField(choices=[(3, '\u6062\u590d'), (2, '\u544a\u8b66\u4e2d'), (1, '\u6b63\u5e38')], default=1),
        ),
    ]
