# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-11-10 12:58
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0009_auto_20181110_2045'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='record',
            options={'get_latest_by': 'utime', 'ordering': ('-utime',)},
        ),
    ]
