# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-11-10 13:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0010_auto_20181110_2058'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='mon_title',
            field=models.CharField(max_length=100),
        ),
    ]
