# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-11-10 14:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0011_auto_20181110_2155'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='ctime',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='group',
            name='utime',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='groupitem',
            name='ctime',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='groupitem',
            name='utime',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='ctime',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='utime',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='record',
            name='ctime',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='record',
            name='utime',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
