# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-11-11 07:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0012_auto_20181110_2204'),
    ]

    operations = [
        migrations.RenameField(
            model_name='groupitem',
            old_name='item_id',
            new_name='mon_id',
        ),
        migrations.AddField(
            model_name='group',
            name='notify_wechat',
            field=models.CharField(default='', max_length=1024),
        ),
    ]
