# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-11-11 11:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0013_auto_20181111_1539'),
    ]

    operations = [
        migrations.AddField(
            model_name='record',
            name='err_info',
            field=models.CharField(blank=True, default='', max_length=1024),
        ),
        migrations.AddField(
            model_name='record',
            name='mon_type_id',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='record',
            name='operator',
            field=models.CharField(blank=True, default='', max_length=256),
        ),
    ]
