# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-11-11 11:23
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0014_auto_20181111_1911'),
    ]

    operations = [
        migrations.RenameField(
            model_name='record',
            old_name='mon_type_id',
            new_name='mon_type',
        ),
    ]
